# config/__init__.py
# 配置模块初始化

from .constants import (
    APP_NAME,
    APP_NAME_EN,
    ASR_MODEL_DIR,
    ASR_MODELS,
    ASSETS_DIR,
    AUDIO_DIR,
    CONFIG_DIR,
    CORE_DIR,
    DEFAULT_AUDIO,
    DEFAULT_CLEANUP,
    DEFAULT_HOTKEYS,
    DEFAULT_HOTKEY_CONFIG,
    DEFAULT_TRANSLATION,
    HOTKEY_PRESETS,
    IS_LINUX,
    IS_MACOS,
    IS_WINDOWS,
    LANGUAGE_NAMES,
    LANGUAGE_PAIRS,
    LOG_DATE_FORMAT,
    LOG_FORMAT,
    LOG_LEVEL,
    LOGS_DIR,
    MODELS_DIR,
    PLATFORM,
    PROJECT_ROOT,
    STORAGE_DIR,
    TRANSLATION_MODEL_DIR,
    TRANSLATION_MODELS,
    VERSION,
    ensure_directories,
    get_config_path,
    get_log_path,
)
from .settings import Settings, get_settings

__all__ = [
    # 常量
    "APP_NAME",
    "APP_NAME_EN",
    "VERSION",
    "PLATFORM",
    "IS_MACOS",
    "IS_WINDOWS",
    "IS_LINUX",
    "PROJECT_ROOT",
    "CORE_DIR",
    "MODELS_DIR",
    "AUDIO_DIR",
    "STORAGE_DIR",
    "LOGS_DIR",
    "CONFIG_DIR",
    "ASSETS_DIR",
    "ASR_MODEL_DIR",
    "TRANSLATION_MODEL_DIR",
    "DEFAULT_HOTKEYS",
    "DEFAULT_HOTKEY_CONFIG",
    "HOTKEY_PRESETS",
    "DEFAULT_AUDIO",
    "DEFAULT_TRANSLATION",
    "DEFAULT_CLEANUP",
    "ASR_MODELS",
    "TRANSLATION_MODELS",
    "LANGUAGE_NAMES",
    "LANGUAGE_PAIRS",
    "LOG_FORMAT",
    "LOG_DATE_FORMAT",
    "LOG_LEVEL",
    # 函数
    "ensure_directories",
    "get_config_path",
    "get_log_path",
    # 类
    "Settings",
    "get_settings",
]
